import Blog1 from "./blog1";
import Blog2 from "./blog2";


const Portfolio_data = [
    {
        id: 1,
        category: "COMPUTER VISION",
        title: "Image Processing and Fourier Transform Techniques for Object Detection and Compression",
        about: "This project explores fundamental image processing techniques and their applications in object detection and image compression. Key tasks include detecting traffic lights and road signs using Hough Transforms, implementing template matching for identifying specific shapes, and utilizing Fourier Transforms for compressing images and applying low-pass filters. The project showcases a comprehensive understanding of manipulating images, detecting objects under varying conditions, and efficiently compressing image data while preserving essential details.",
        tech_used: "Python, OpenCV, NumPy, Matplotlib, Hough Transforms, Template Matching, Discrete Fourier Transform (DFT), Fast Fourier Transform (FFT)",
        image: "skill1.png",
        content: <Blog1/>,
        Github_link: 'https://github.com/ssingh448/Computer_Vision_Projects',
        PDF_Link: '',
        IsPDF: '',
    },
    // {
    //     id: 2,
    //     category: "COMPUTER VISION",
    //     title: "",
    //     about: "",
    //     tech_used: "",
    //     image: "skill1.png",
    //     content: <Blog1/>,
    //     Github_link: 'https://github.com/ssingh448/Computer_Vision_Projects',
    //     PDF_Link: '',
    //     IsPDF: '',
    // },
    {
        id: 2,
        category: "COMPUTER VISION",
        title: "Augmented Reality and Image Stitching in Computer Vision",
        about: "This project delves into the core concepts of augmented reality (AR) and image stitching, focusing on the detection of markers and their transformation across various images and videos. The project involves implementing techniques such as Harris corner detection for identifying markers, projective geometry for transforming and inserting images into specific areas, and stitching multiple images to create a seamless panorama. Additionally, the project includes robust marker detection in both simulated and real-life scenes and processes video frames to insert dynamic content into live feeds.",
        tech_used: "Python, OpenCV, NumPy, Projective Geometry, Harris Corner Detection, Homography, Video Processing",
        image: "skill1.png",
        content: <Blog1/>,
        Github_link: 'https://github.com/ssingh448/Computer_Vision_Projects',
        PDF_Link: '',
        IsPDF: '',
    },
    {
        id: 2,
        category: "COMPUTER VISION",
        title: "Motion Detection using Hierarchical Lucas-Kanade Method",
        about: "This project focuses on detecting motion in image sequences by implementing the Hierarchical Lucas-Kanade method to compute dense optical flow fields. The project involves key tasks such as calculating image gradients, building Gaussian and Laplacian pyramids, and warping images based on computed flow vectors. Additionally, frame interpolation techniques are applied to generate intermediate frames between given image sequences. The approach emphasizes understanding pixel movement as flow vectors and the benefits of using a pyramidal approach for handling large displacements.",
        tech_used: "Python, NumPy, OpenCV, Matplotlib",
        image: "skill1.png",
        content: <Blog1/>,
        Github_link: 'https://github.com/ssingh448/Computer_Vision_Projects',
        PDF_Link: '',
        IsPDF: '',
    },
    {
        id: 2,
        category: "COMPUTER VISION",
        title: "Object Tracking and Pedestrian Detection System",
        about: "This project focuses on developing a robust Object Tracking and Pedestrian Detection system using Kalman and Particle Filters. Implementing these algorithms from scratch, the system accurately tracks moving objects across image sequences and video streams. By applying advanced image processing techniques, it efficiently locates and follows objects, even in complex and dynamic environments. OpenCV was leveraged for essential image processing, excluding the core tracking algorithms, which were custom-built.",
        tech_used: "Python, OpenCV, NumPy, Kalman Filters, Particle Filters, Image Processing Techniques",
        image: "skill1.png",
        content: <Blog1/>,
        Github_link: 'https://github.com/ssingh448/Computer_Vision_Projects',
        PDF_Link: '',
        IsPDF: '',
    },
    {
        id: 2,
        category: "COMPUTER VISION",
        title: "Recognition and Detection using PCA, Boosting, and Viola-Jones",
        about: "This project implements a comprehensive face recognition and detection system using Principal Component Analysis (PCA), Boosting (AdaBoost), and the Viola-Jones algorithm. Starting with PCA, the project reduces the dimensionality of facial images to create eigenfaces, which are then used for classification. The Boosting algorithm enhances the classification accuracy by combining multiple weak classifiers. Finally, Haar-like features are generated and used in the Viola-Jones algorithm for real-time face detection. The entire solution was developed from scratch without relying on OpenCV’s dedicated functions.",
        tech_used: "Python, Numpy, Numba, Matplotlib, Scikit-Learn",
        image: "skill1.png",
        content: <Blog1/>,
        Github_link: 'https://github.com/ssingh448/Computer_Vision_Projects',
        PDF_Link: '',
        IsPDF: '',
    },
    {
        id: 2,
        category: "COMPUTER VISION",
        title: "Stereo Correspondence Algorithms for Disparity Map Generation",
        about: "Implemented two stereo correspondence algorithms for generating disparity maps: a simple Sum of Squared Differences (SSD) approach and an advanced energy optimization technique using Loopy Belief Propagation over Markov Random Fields. The disparity maps produced are evaluated against ground truth data from the Middlebury Stereo Dataset, with detailed performance analysis and comparison between methods. The results highlight the trade-offs between accuracy and computational efficiency in stereo vision algorithms.",
        tech_used: "Python, Custom implementations for SSD, Loopy Belief Propagation, and Markov Random Fields",
        image: "skill1.png",
        content: <Blog1/>,
        Github_link: 'https://github.com/ssingh448/Computer_Vision_Projects',
        PDF_Link: '',
        IsPDF: ',REPORT',
    },
    {
        id: 2,
        category: "APPLICATION",
        title: "Mobile app landing design & maintain",
        about: "about me",
        tech_used : "\"\t•\tProgramming Languages: Python\n" +
            "\t•\tLibraries/Tools: OpenCV, NumPy, Matplotlib\n" +
            "\t•\tAlgorithms: Hough Transforms, Template Matching, Discrete Fourier Transform (DFT), Fast Fourier Transform (FFT)\"",
        image: "skill1.png",
        content: <Blog2/>,
        Github_link: 'https://stackoverflow.com/questions/10657315/git-merge-left-head-marks-in-my-files',
        PDF_Link: '',
        IsPDF: '',
    },
    {
        id: 3,
        category: "PHOTOSHOP",
        title: "Logo design creativity & Application ",
        about: "about me",
        tech_used : "",
        image: "skill1.png",
        content: <Blog1/>,
        Github_link: 'https://stackoverflow.com/questions/10657315/git-merge-left-head-marks-in-my-files',
        PDF_Link: '',
        IsPDF: '',
    },
    {
        id: 4,
        category: "FIGMA",
        title: "Mobile app landing design & Services",
        about: "about me",
        tech_used : "",
        image: "skill1.png",
        content: <Blog1/>,
        Github_link: 'https://stackoverflow.com/questions/10657315/git-merge-left-head-marks-in-my-files',
        PDF_Link: '',
        IsPDF: '',
    },
    {
        id: 5,
        category: "WEB DESIGN",
        title: "Design for tecnology & services",
        about: "about me",
        tech_used : "",
        image: "skill1.png",
        content: <Blog1/>,
        Github_link: 'https://stackoverflow.com/questions/10657315/git-merge-left-head-marks-in-my-files',
        PDF_Link: '',
        IsPDF: '',
    },
    {
        id: 6,
        category: "WEB DESIGN",
        title: "App for tecnology & services",
        about: "about me",
        tech_used : "",
        image: "skill1.png",
        content: <Blog1/>,
        Github_link: 'https://stackoverflow.com/questions/10657315/git-merge-left-head-marks-in-my-files',
        PDF_Link: '',
        IsPDF: '',
    },
]
export default Portfolio_data